### ISSUE TITLE
ColorOS13 无法正常使用

### ISSUE THREAD

**Issue by LycanDos** [Kr328/Riru-ClipboardWhitelist#29]
v23导致系统剪切板无法粘贴,其他正常
v24 大部分 app 无法启动
[logcat.log](https://github.com/Kr328/Riru-ClipboardWhitelist/files/10704335/logcat.log)
其他软件报错:
java.lang.IllegalStateException: Binder interceptor disabled
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3048)
 at android.os.Parcel.createException(Parcel.java:3024)
 at android.os.Parcel.readException(Parcel.java:3007)
 at android.os.Parcel.readException(Parcel.java:2949)
 at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:363)
 at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:207)
 at y5.l.b(Unknown Source:8)
 at k5.n$b.n(Unknown Source:51)
 at k5.n$b.g(Unknown Source:12)
 at a3.a.q(Unknown Source:3)
 at a3.a.v(Unknown Source:103)
 at k5.n.n(Unknown Source:110)
 at v6.a.f(Unknown Source:8)
 at k7.j0.run(Unknown Source:100)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:240)
 at android.os.Looper.loop(Looper.java:351)
 at android.app.ActivityThread.main(ActivityThread.java:8379)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
 Suppressed: k7.h0: [n1{Cancelling}@52eea6f, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
 at com.github.kr328.zloader.internal.Loader.callExecTransact(Loader.java:3)
 at com.github.kr328.zloader.BinderInterceptors$BinderProxy.transact(BinderInterceptors.java:2)
 at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:362)
 at com.github.kr328.clipboard.ClipboardProxy.getPrimaryClip(ClipboardProxy.java:7)
 at android.content.IClipboard$Stub.onTransact(IClipboard.java:201)

**Comment by a0iwguf09u** [comment]
+1
我ColorOS12 用v23就正常了
