### ISSUE TITLE
Android 14 疯狂闪退

### ISSUE THREAD

**Issue by lupohan44** [Kr328/Riru-ClipboardWhitelist#46]
报错日志
```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: google
[Device Model]: Pixel 7 Pro
[Display]: UQ1A.231205.015
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN_#Hans
[Process ID]: 21068
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.github.kr328.clipboard
[Version Name]: v26
[Version Code]: 26
[Target SDK]: 34
[Min SDK]: 29
[Error Type]: JVM
[Crash Time]: 2024-01-04T16:07:47.218
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6897)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by sky96111** [comment]
Same problem on OnePlus 12 OxygenOS 14
KernelSU with ZygiskNext

logcat:
````
04-11 21:46:57.849  3277  5281 D FlexibleWindowManager: no reused task found for ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity
04-11 21:46:57.854  3277  5281 I OplusScreenSecurityMask: onStackAdded task = Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} record = null displayId = 0
04-11 21:46:57.856  3277  5281 D TaskFragmentExtImpl: add ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378} to mActivityRecordSum = Counter{ com.github.kr328.clipboard/.MainActivity(1) }
04-11 21:46:57.857  3277  5281 D OplusStartingWindowManager: reviseWindowFlagsForStarting activityRecord =:ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}, RUS version:20231110
04-11 21:46:57.858  3277  5281 D ActivityTaskManager: getStartingWindowType: newTask=true, taskSwitch=true, processRunning=false, allowTaskSnapshot=true, activityCreated=false, activityAllDrawn=false ,snapshot=null, record:ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.858  3277  5281 D OplusZoomWindowRUSConfigManager: isSupportZoomModeWithPolicyLocked: target = com.github.kr328.clipboard/.MainActivity
04-11 21:46:57.858  3277  5281 D OplusZoomWindowRUSConfigManager: targetPkg = com.github.kr328.clipboard
04-11 21:46:57.860  3277  4101 E UAH_JNI : uah_event_acquire ! cmdId: 1 ,strPkg: com.github.kr328.clipboard, strIdent: com.android.server.wm, timeout: 2000
04-11 21:46:57.860  3277  4101 I [UAH_CLIENT]: UahEventAcquire, cmdid:1, pkg:com.github.kr328.clipboard, identity:com.android.server.wm
04-11 21:46:57.860  4254  4463 W ShellStartingWindow: Failed creating package context with package name com.github.kr328.clipboard for user 0
04-11 21:46:57.860  4254  4463 W ShellStartingWindow: android.content.pm.PackageManager$NameNotFoundException: Application package com.github.kr328.clipboard not found
04-11 21:46:57.860  3277  5281 D ActivityTaskManager: notifyTaskAdded, task: Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} trace:com.android.server.wm.RecentTasks.add:1269 com.android.server.wm.ActivityStarter.startActivityInner:2328 com.android.server.wm.ActivityStarter.startActivityUnchecked:1740 com.android.server.wm.ActivityStarter.executeRequest:1524 com.android.server.wm.ActivityStarter.execute:830
04-11 21:46:57.861  4254  4395 V WindowManagerShell: Transition requested: android.os.BinderProxy@7c4cc33 TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=378 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.kr328.clipboard/.MainActivity mCallingUid=10198 } baseActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} topActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} origActivity=null realActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} numActivities=1 lastActiveTime=509734 supportsSplitScreenMultiWindow=true supportsMultiWindow=true supportsPocketStudioMultiWindow=true isInFlexibleEmbedded = false uid = 10309 pid = 0 resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@774abf0} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 120 - 0, 0) topActivityInfo=ActivityInfo{4b08569 com.github.kr328.clipboard.MainActivity} launchCookies=[android.os.BinderProxy@4fbee] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false topActivityInSizeCompat=false topActivityInOplusCompatMode=false topActivityEligibleForLetterboxEducation= false topActivityLetterboxed= false isFromDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden locusId= null topActivityLetterboxInsets=Rect(0, 0 - 0, 0)}, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@ef5f88f, appThread = android.app.IApplicationThread$Stub$Proxy@e10971c, debugName = QuickstepLaunch }, displayChange = null }
04-11 21:46:57.862  3277  5281 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.kr328.clipboard/.MainActivity bnds=[534,706][780,997] (has extras) mCallingUid=10198} with LAUNCH_MULTIPLE from uid 10198 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
04-11 21:46:57.867  3277  8627 I OplusHansManager : front pkg: com.github.kr328.clipboard, uid: 10309, prev pkg: com.android.launcher, prev uid: 10198
04-11 21:46:57.867  3277  8627 D ActivityTaskManager: setVisibility(Token{4275a82 ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}}, visible=true) defer commitVisibility for transition collecting
04-11 21:46:57.867  3277  4271 I Osense-BaseDecisionMaker: notifySceneToAthenaPolicy: SCENE_APP_SWITCH, bundle: Bundle[{prevPkgName=com.android.launcher, curUid=10309, curPkgName=com.github.kr328.clipboard, prevUid=10198}]
04-11 21:46:57.868  3277  4606 I OplusResourcePreloadManager: resume pkg: com.github.kr328.clipboard, uid:10309, prev pkg: com.android.launcher, prev uid: 10198
04-11 21:46:57.872  3277  3582 I ActivityManager: Start proc 16270:com.github.kr328.clipboard/u0a309 for next-top-activity {com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity}
04-11 21:46:57.873  1663  1663 E qspmHal : setAppInfoH atPid = 16270, gpuFname:com.github.kr328.clipboard, gpuFver:261
04-11 21:46:57.888  7041  7092 D BinderSender: sendBinder to uid 10309: packages=com.github.kr328.clipboard
04-11 21:46:57.901  3277  8627 D ResourcesManagerCache: For package com.github.kr328.clipboard we got cacheList [null] appInfoExt is null ? false hasFeature ? false
04-11 21:46:57.902  3277  8627 D WindowManager: updateOrientation: mLastOrientation = SCREEN_ORIENTATION_NOSENSOR(5) newOrientation = SCREEN_ORIENTATION_UNSPECIFIED(-1) forceUpdate = true LastOrientationSource = ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.902  3277  8627 D ActivityTaskManager: setVisibility(Token{4275a82 ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}}, visible=true) defer commitVisibility for transition collecting
04-11 21:46:57.903  3277  8627 D OplusCameraStartupOptimization: cameraPreopenIfNeed, r = ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.903  3277  8627 D OplusCameraStartupOptimization: needOptimizeForCamera bNeedOptimize:false clsName: com.github.kr328.clipboard/.MainActivity
04-11 21:46:57.905  3277  8627 D ActivityTaskManager: onWindowFocusChanged Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} would transfer to compact
04-11 21:46:57.905  3277  8627 I InputDispatcher: setFocusedApplication displayId=0 ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.905  3277  8627 D ActivityTaskManager: NFW_setLastResumedActivityUncheckLocked:true r:ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.907  3277  8627 D FlexibleTaskController: onTaskFocusChanged prevTask:Task{28b5586 #5 type=home I=com.android.launcher/.Launcher} ,currentTask:Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard}
04-11 21:46:57.907  3277  4101 E UAH_JNI : uah_event_acquire ! cmdId: 0 ,strPkg: com.github.kr328.clipboard, strIdent: com.android.server.wm, timeout: 600
04-11 21:46:57.907  3277  4101 I [UAH_CLIENT]: UahEventAcquire, cmdid:0, pkg:com.github.kr328.clipboard, identity:com.android.server.wm
04-11 21:46:57.907  3277  8627 I OplusAppSwitchManagerService: appswitch hasProcess ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.908  3277  8627 I OplusAppSwitchManagerService: appswitch hasProcess ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}
04-11 21:46:57.909  3277  4734 D OplusAppSwitchListener: Detect com.github.kr328.clipboard switch to foreground
04-11 21:46:57.909  4168  4190 V DCSEX-AppSwitchManager: OnAppSwitchObserver: onAppExit, resuming = com.github.kr328.clipboard, target = com.android.launcher, is ResumingFirstStart =  true, is ResumingMultiApp =  false, extensionInfo =  Bundle[mParcelledData.dataSize=84]
04-11 21:46:57.910  3277  4734 D OplusEapManager: mTargetEnterName :com.github.kr328.clipboard
04-11 21:46:57.910  3277  4734 D OplusLatencyOptimizerManager: enter pkg: com.github.kr328.clipboard isPrevBlackAppTop: false mIsBlackAppTop: false
04-11 21:46:57.910  3277  4734 D VRR [OPlusFrontAppManager]: OnAppSwitchObserver: onAppEnter , info.targetName = com.github.kr328.clipboard
04-11 21:46:57.910  3277  4734 D VRR [OPlusFrontAppManager]: packageName: com.github.kr328.clipboard
04-11 21:46:57.910  4168  4190 V DCSEX-AppSwitchManager: OnAppSwitchObserver: onAppEnter, launchedFrom =  com.android.launcher, target =  com.github.kr328.clipboard, is firstStart =  true, is multiApp =  false, extensionInfo =  Bundle[mParcelledData.dataSize=140]
04-11 21:46:57.910  3277  3815 I Athena  : RecordAppChangeAction: updateRecentlyUsedApp fgAppRecord=packageName:com.github.kr328.clipboard, uid:10309, userId:0, isTop=true, fgElapsedTime=509784, bgElapsedTime=0, fgElapsedDur=509785, bgElapsedDur=0
04-11 21:46:57.911  3277  3611 D VRR [OPlusRefreshRateService]: handleFrontAppChange pkgName: com.github.kr328.clipboard
04-11 21:46:57.911  3277  3611 D VRR [OPlusExternalRefreshRateManager]: setFrontPackageName pkgName: com.github.kr328.clipboard CurPkgName: null
04-11 21:46:57.911  3277  3611 D VRR [OPlusGameStatusManager]: setFrontPackageName pkgName: com.github.kr328.clipboard CurPkgName: null
04-11 21:46:57.911  3277  3611 D VRR [OPlusGameStatusManager]: setGameStop: CurPkgNamecom.github.kr328.clipboard GameController: null
04-11 21:46:57.911  4770  4883 I Athena  : AthenaDynamicReceiver: pre_app:com.android.launcher, next_app:com.github.kr328.clipboard(10309|16270)
04-11 21:46:57.911  4168 10038 D DCSEX-AppLaunchEventRecorder: onAppSwitch from = com.android.launcher to = com.github.kr328.clipboard
04-11 21:46:57.911  3277  8627 D ActivityTaskManager: setVisibility(Token{4275a82 ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}}, visible=true) defer commitVisibility for transition collecting
04-11 21:46:57.912  8489  8657 D SceneSDK.1.0.4-SNAPSHOT.8489.DeepThinkerAppSwitchAbility: onAppSwitchEvent: AppSwitchEvent(timeStamp=1712843217910, eventType=2, targetName=com.android.launcher, firstStart=false, multiApp=false, windowMode=0, resumingPackageName=com.github.kr328.clipboard, resumingActivityName=com.github.kr328.clipboard.MainActivity, isResumingMultiApp=false, isResumingFirstStart=true)
04-11 21:46:57.911  4254  5382 I SystemUi--Keyguard: ChargingAnimationImpl-->onAppExit , oplusAppExitInfo : OplusAppExitInfo = {  targetName = com.android.launcher hasResumingActivity = true resumingPackageName = com.github.kr328.clipboard resumingActivityName = com.github.kr328.clipboard.MainActivity resumingWindowMode = 1 isResumingMultiApp = false isResumingFirstStart = true extension = Bundle[mParcelledData.dataSize=84]}
04-11 21:46:57.912  7761  9715 W Battery : ThermalControlUtils: mForegroundPkg=com.github.kr328.clipboard
04-11 21:46:57.913  3277  4120 D ORBrightnessMarvelsDataCollector: Runnable-MarvelsAppEnterInfo[2024-04-11 21:46:57,com.github.kr328.clipboard,569.0]
04-11 21:46:57.913  3277  4120 D ORBrightnessMarvelsModel: Fetch key:1, data:0:com.github.kr328.clipboard;1:569.0
04-11 21:46:57.913  3277  3589 E OplusThermalStats: Error getting package info: com.github.kr328.clipboard
04-11 21:46:57.914  8489  8657 I metis_v2_AppSwitchDataCollector: AppExitEvent =  com.android.launcher, NextAppName = com.github.kr328.clipboard
04-11 21:46:57.918  8489  8657 D metis_v2_AppInfoUtils: getTopAppInfos is [OplusAppInfo{windowingMode=1, activityType=1, taskId=378, appBounds=Rect(0, 0 - 1080, 2376), appInfo=ApplicationInfo{375605 com.github.kr328.clipboard}, topActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity}, displayId=0, orientation=-1, userId=0, launchedFromPackage=com.android.launcher, isRootActivity=true, extension=Bundle[EMPTY_PARCEL]}]
04-11 21:46:57.920 16270 16270 D nativeloader: Configuring clns-shared-4 for other apk /system/app/ClipboardWhitelist/ClipboardWhitelist.apk. target_sdk_version=34, uses_libraries=, library_path=/system/app/ClipboardWhitelist/lib/arm64:/system/lib64:/system_ext/lib64, permitted_path=/data:/mnt/expand:/data/user/0/com.github.kr328.clipboard:/system/app/ClipboardWhitelist:/system/lib64:/system_ext/lib64
04-11 21:46:57.921  3277  5073 D OplusBatteryServiceFeature: setSmartCoolDown: coolDown = 7, normalCoolDown = 7, pkgName = com.github.kr328.clipboard
04-11 21:46:57.921 16270 16270 W ConfigurationController: updateLocaleList app resources is null: com.github.kr328.clipboard
04-11 21:46:57.922  8489  8657 D SceneSDK.1.0.4-SNAPSHOT.8489.DeepThinkerAppSwitchAbility: onAppSwitchEvent: AppSwitchEvent(timeStamp=1712843217919, eventType=1, targetName=com.github.kr328.clipboard, firstStart=true, multiApp=false, windowMode=1, resumingPackageName=, resumingActivityName=, isResumingMultiApp=false, isResumingFirstStart=false)
04-11 21:46:57.922  8489  8657 I metis_v2_AppSwitchDataCollector: AppEnterEvent =  com.github.kr328.clipboard, windowMode = 1
04-11 21:46:57.924 16270 16270 V GraphicsEnvironment: ANGLE GameManagerService for com.github.kr328.clipboard: false
04-11 21:46:57.924 16270 16270 V GraphicsEnvironment: com.github.kr328.clipboard is not listed in per-application setting
04-11 21:46:57.925  7041 12665 D BinderSender: sendBinder to uid 10309: packages=com.github.kr328.clipboard
04-11 21:46:57.925 16270 16270 E AndroidRuntime: Process: com.github.kr328.clipboard, PID: 16270
04-11 21:46:57.925 16270 16270 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application android.app.Application package com.github.kr328.clipboard: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
04-11 21:46:57.925  3277  4563 D OplusAppStartupMonitor: notifyUnstableAppInfo: Bundle[{unstableTime=1712843217925, reason=crash, userId=0, exceptionMsg=Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference, exceptionClass=java.lang.NullPointerException, app_channel_type=unstable, packageName=com.github.kr328.clipboard, unstable_restrict_switch=true}]
04-11 21:46:57.926  8489  8657 D metis_v2_AppInfoUtils: getTopAppInfos is [OplusAppInfo{windowingMode=1, activityType=1, taskId=378, appBounds=Rect(0, 0 - 1080, 2376), appInfo=ApplicationInfo{a3565a com.github.kr328.clipboard}, topActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity}, displayId=0, orientation=-1, userId=0, launchedFromPackage=com.android.launcher, isRootActivity=true, extension=Bundle[EMPTY_PARCEL]}]
04-11 21:46:57.927  1795 15736 D AudioFlingerExtImpl: AudioFlingerExtImpl oplusSetParameters: keyvalue onForegroundActivitiesChanged=com.github.kr328.clipboard:foreground:1
04-11 21:46:57.927  1795 15736 D AudioFlingerExtImpl: updateForegroundInfo() mForegroundActivitiesPkgMap[com.github.kr328.clipboard] = 1
04-11 21:46:57.927  3277  8627 W OplusEapManager handleErrorInfo sendEvent: : com.github.kr328.clipboard happenedcrash
04-11 21:46:57.927  3277  5627 D OplusBatteryServiceFeature: setSmartCoolDown: coolDown = 7, normalCoolDown = 7, pkgName = com.github.kr328.clipboard
04-11 21:46:57.928  3277  8627 W ActivityTaskManager:   Force finishing activity com.github.kr328.clipboard/.MainActivity
04-11 21:46:57.928  3277  4101 E UAH_JNI : uah_event_acquire ! cmdId: 0 ,strPkg: com.github.kr328.clipboard, strIdent: com.android.server.wm, timeout: 600
04-11 21:46:57.928  3277  4101 I [UAH_CLIENT]: UahEventAcquire, cmdid:0, pkg:com.github.kr328.clipboard, identity:com.android.server.wm
04-11 21:46:57.928  3277  8627 D FlexibleTaskController: onTaskFocusChanged prevTask:Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} ,currentTask:Task{28b5586 #5 type=home I=com.android.launcher/.Launcher}
04-11 21:46:57.929  3277  8627 D ActivityTaskManager: setVisibility(Token{4275a82 ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378 f}}}, visible=false) defer commitVisibility for transition collecting
04-11 21:46:57.931  3277  5627 D OplusDisplayManagerServiceEnhance: OplusDisplayManagerServiceEnhance setSpecBrightness gear = 0 reason = com.github.kr328.clipboard@temperature@31@normal rate = -1
04-11 21:46:57.931  3277  3605 D OplusFeatureTemperatureLimitBrightness: new parameter!ControlInfo:[ gear = 0 reason = com.github.kr328.clipboard@temperature@31@normal brightness = 10239 package = com.github.kr328.clipboard type = temperature temperature = 31 priority = normal rate = -1] HadDragPoint = false mode = 1
04-11 21:46:57.934  7761  9719 D UAH-UahAdaptHelper: adaptSetNotification identity = ThermalControlUtilssrc = 4 , type 0 ,p1 = 0 ,p2 = 31 ,p3 = 3 ,p4 =com.github.kr328.clipboard
04-11 21:46:57.939  3277  9205 I ActivityManager: Process com.github.kr328.clipboard (pid 16270) has died: fg  TOP
04-11 21:46:57.940  1663  1663 E qspmHal : setAppInfoH atPid = 16270, gpuFname:com.github.kr328.clipboard, gpuFver:260
04-11 21:46:57.941  1795 15736 D AudioFlingerExtImpl: AudioFlingerExtImpl oplusSetParameters: keyvalue onForegroundActivitiesChanged=com.github.kr328.clipboard:foreground:0
04-11 21:46:57.944  3277  9205 D ActivityTaskManager: removeAppToken: ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378 f}} delayed=true parent=Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} animating=true Callers=com.android.server.wm.DisplayContent.removeAppToken:1655 com.android.server.wm.ActivityRecord.removeFromHistory:4581 com.android.server.wm.ActivityRecord.handleAppDied:4911 com.android.server.wm.WindowProcessController.handleAppDied:1523
04-11 21:46:57.944  3277  9205 D ActivityTaskManager: Clearing startingData for token=ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378 f}}
04-11 21:46:57.945  3277  9205 I OplusScreenSecurityMask: onStackRemoved task = Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} record = null displayId = 0
04-11 21:46:57.945  3277  9205 D ActivityTaskManager: notifyTaskRemoved, task: Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard} trace:com.android.server.wm.RecentTasks.remove:1353 com.android.server.wm.Task.cleanUpResourcesForDestroy:772 com.android.server.wm.Task.onParentChanged:1204 com.android.server.wm.WindowContainer.setParent:615 com.android.server.wm.WindowContainer.removeChild:826
04-11 21:46:57.945  3277  9205 D OplusAlwaysAliveManager: removing: 378, ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity}
04-11 21:46:57.945  3277  9205 D TaskFragmentExtImpl: remove ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t-1 f}} to mActivityRecordSum = Counter{ }
04-11 21:46:57.946  3277  9205 I OplusHansManager : front pkg: com.android.launcher, uid: 10198, prev pkg: com.github.kr328.clipboard, prev uid: 10309
04-11 21:46:57.948  3277  4271 I Osense-BaseDecisionMaker: notifySceneToAthenaPolicy: SCENE_LAUNCHER, bundle: Bundle[{prevPkgName=com.github.kr328.clipboard, curUid=10198, curPkgName=com.android.launcher, prevUid=10309}]
04-11 21:46:57.948  3277  4606 I OplusResourcePreloadManager: resume pkg: com.android.launcher, uid:10198, prev pkg: com.github.kr328.clipboard, prev uid: 10309
04-11 21:46:57.954  3277  3523 V WindowManager: Sent Transition #28 createdAt=04-11 21:46:57.846 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=378 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.kr328.clipboard/.MainActivity mCallingUid=10198 } baseActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} topActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} origActivity=null realActivity=ComponentInfo{com.github.kr328.clipboard/com.github.kr328.clipboard.MainActivity} numActivities=1 lastActiveTime=509734 supportsSplitScreenMultiWindow=true supportsMultiWindow=true supportsPocketStudioMultiWindow=true isInFlexibleEmbedded = false uid = 10309 pid = 0 resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{1bb1030 Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 120 - 0, 0) topActivityInfo=ActivityInfo{912cd91 com.github.kr328.clipboard.MainActivity} launchCookies=[android.os.BinderProxy@b4b4a9] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=false isVisible=false isVisibleRequested=false isSleeping=false topActivityInSizeCompat=false topActivityInOplusCompatMode=false topActivityEligibleForLetterboxEducation= false topActivityLetterboxed= false isFromDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden locusId= null topActivityLetterboxInsets=Rect(0, 0 - 0, 0)}, remoteTransition = RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@e41b7da, appThread = android.app.IApplicationThread$Stub$Proxy@49be40b, debugName = QuickstepLaunch }, displayChange = null }
04-11 21:46:57.956  3277  8627 D OplusTransitionAnimationManager: commitVisibilityWhenFinishTransition type=1, ar.isVisibleRequested=false, ar.isVisible=false, ar.isVisibleRequested=false, ar=ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t-1 f}} ar type 1 ar state :DESTROYED displayid :-1, participants={Task{28b5586 #5 type=home I=com.android.launcher/.Launcher}, ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t-1 f}}, Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard}, ActivityRecord{541c444 u0 com.android.launcher/.Launcher t5}, WallpaperWindowToken{9a6271a token=android.os.Binder@eb3f1c5}, Task{c0706e6 #1 type=home}}
04-11 21:46:57.956  3277  8627 D OplusTransitionAnimationManager: commitVisibilityWhenFinishTransition type=1, ar.isVisibleRequested=true, ar.isVisible=true, ar.isVisibleRequested=true, ar=ActivityRecord{541c444 u0 com.android.launcher/.Launcher t5} ar type 2 ar state :RESUMED displayid :0, participants={Task{28b5586 #5 type=home I=com.android.launcher/.Launcher}, ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t-1 f}}, Task{405b1cd #378 type=standard A=10309:com.github.kr328.clipboard}, ActivityRecord{541c444 u0 com.android.launcher/.Launcher t5}, WallpaperWindowToken{9a6271a token=android.os.Binder@eb3f1c5}, Task{c0706e6 #1 type=home}}
04-11 21:46:57.962  1803  1803 D Layer   : reparent to null sequence=318, seq[0], name=ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t378}#318
04-11 21:46:58.429  3277  3526 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{3fda0f7 u0 com.github.kr328.clipboard/.MainActivity t-1 f}}
04-11 21:46:58.431  3277  4734 D OplusAppSwitchListener: Detect com.github.kr328.clipboard switch to background
04-11 21:46:58.431  3277  4734 D OplusFeatureReduceBrightness: onAppExit , info = com.github.kr328.clipboard
04-11 21:46:58.431  3277  4734 D OplusEapManager: mTargetExitName :com.github.kr328.clipboard
04-11 21:46:58.431  3277  4734 D VRR [OPlusFrontAppManager]: OnAppSwitchObserver: onAppExit , info.targetName = com.github.kr328.clipboard
04-11 21:46:58.432  4168  4190 V DCSEX-AppSwitchManager: OnAppSwitchObserver: onAppExit, resuming = com.android.launcher, target = com.github.kr328.clipboard, is ResumingFirstStart =  false, is ResumingMultiApp =  false, extensionInfo =  Bundle[mParcelledData.dataSize=84]
04-11 21:46:58.433  3277  3815 I Athena  : RecordAppChangeAction: updateRecentlyUsedApp bgAppRecord=packageName:com.github.kr328.clipboard, uid:10309, userId:0, isTop=false, fgElapsedTime=509784, bgElapsedTime=510307, fgElapsedDur=523, bgElapsedDur=0
04-11 21:46:58.434  4770 13654 I Athena  : AthenaDynamicReceiver: pre_app:com.github.kr328.clipboard, next_app:com.android.launcher(10198|4845)
04-11 21:46:58.435  4168 10038 D DCSEX-AppLaunchEventRecorder: onAppSwitch from = com.github.kr328.clipboard to = com.android.launcher
04-11 21:46:58.435  3277  3611 D VRR [OPlusExternalRefreshRateManager]: setFrontPackageName pkgName: com.android.launcher CurPkgName: com.github.kr328.clipboard
04-11 21:46:58.435  3277  3611 D VRR [OPlusGameStatusManager]: setFrontPackageName pkgName: com.android.launcher CurPkgName: com.github.kr328.clipboard
04-11 21:46:58.436  3277  8627 D VRR [OPlusRefreshRateService]:  setFrameRateTargetControl [ 0.0 , com.github.kr328.clipboard , false , com.oplus.battery ]
04-11 21:46:58.436  8489  8657 D SceneSDK.1.0.4-SNAPSHOT.8489.DeepThinkerAppSwitchAbility: onAppSwitchEvent: AppSwitchEvent(timeStamp=1712843218435, eventType=2, targetName=com.github.kr328.clipboard, firstStart=false, multiApp=false, windowMode=0, resumingPackageName=com.android.launcher, resumingActivityName=com.android.launcher.Launcher, isResumingMultiApp=false, isResumingFirstStart=false)
04-11 21:46:58.436  8489  8657 I metis_v2_AppSwitchDataCollector: AppExitEvent =  com.github.kr328.clipboard, NextAppName = com.android.launcher
04-11 21:46:58.438  8489  8657 D metis_v2_AppSwitchDataCollector: Delete Top Application: com.github.kr328.clipboard
04-11 21:46:58.438  3277  8627 D VRR [OPlusExternalRefreshRateManager]:  [FRTC] FrameRate : 0 com.github.kr328.clipboard false com.oplus.battery 0 1000
04-11 21:46:58.438  3277  3611 D VRR [OPlusSurfaceFlingerController]:  add frtc FrameRate : 0 com.github.kr328.clipboard false com.oplus.battery
04-11 21:46:58.438  1803  2113 I VRR [FRTC]: setFrameRateTarget with [0, com.github.kr328.clipboard, 0, com.oplus.battery, 1, 0, 1000]
04-11 21:46:58.439  1803  2113 W VRR [FRTC]: invalid param { fps 0, proc_name com.github.kr328.clipboard, strict_mode 0, description com.oplus.battery, proc_id 0, rate_status 0, backend Surface, version 1, pid 0, uid 1000, overrideRefreshRate 0, backendRefreshRate 0, enable at 2024-04-11 21:46:58, disable waiting } for current status.
````

**Comment by alexhulbert** [comment]
Fixed it https://github.com/alexhulbert/zygisk-clipboard-whitelist-next/
